name: Test Discord Notification

on:
  workflow_dispatch:  # Manual trigger

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  test-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send test notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD_WEBHOOK }}
          title: "🔔 Test Notification - HelixZone"
          description: |
            **Test Message:** If you see this, Discord notifications are working! 🎉
            
            This is a test message from the HelixZone CI/CD system.
            Channel ID: 1202329110102425641
            Webhook Name: HelixZone CI/CD
          color: 0x17A2B8
          username: "HelixZone CI" 